/* ---------------------------------------------------------------------------
   Anglican Church of Nigeria — administrative mapping.
   14 provinces × 176 dioceses (per Church of Nigeria records).
   Each diocese is locked to its province. The registration form cascades
   diocese choices from the chosen province. Selecting "Other" exposes a
   free-text input for the diocese.
   --------------------------------------------------------------------------- */

export const PROVINCE_DIOCESE_MAP = {
  'Province of Aba': [
    'Aba',
    'Aba Ngwa North',
    'Arochukwu/Ohafia',
    'Isiala-Ngwa',
    'Isiala-Ngwa South',
    'Isikwuato',
    'Ngbo',
    'Ukwa',
    'Umuahia',
  ],
  'Province of Abuja': [
    'Abuja',
    'Gwagwalada',
    'Keffi',
    'Kubwa',
    'Lafia',
    'Nasarawa',
  ],
  'Province of Bendel': [
    'Asaba',
    'Benin',
    'Esan',
    'Etsako',
    'Ika',
    'Ishan',
    'Northern Izon',
    'Ozoro',
    'Sabongidda-Ora',
    'Sapele',
    'Ughelli',
    'Warri',
    'Western Izon',
  ],
  'Province of Enugu': [
    'Abakaliki',
    'Afikpo',
    'Awgu/Aninri',
    'Eha-Amufu',
    'Enugu',
    'Enugu North',
    'Ikwo',
    'Nike',
    'Nsukka',
    'Oji River',
    'Udi',
  ],
  'Province of Ibadan': [
    'Egba',
    'Egba West',
    'Ibadan',
    'Ibadan North',
    'Ibadan South',
    'Ife',
    'Ife East',
    'Ilesa',
    'Ilesa South West',
    'Ogbomoso',
    'Oke-Ogun',
    'Oke-Osun',
    'Osun',
    'Osun North',
    'Osun North East',
    'Oyo',
    'Oyo South',
  ],
  'Province of Jos': [
    'Bauchi',
    'Bukuru',
    'Damaturu',
    'Dutse',
    'Gombe',
    'Jalingo',
    'Jos',
    'Langtang',
    'Maiduguri',
    'Pankshin',
    'Takum',
    'Yola',
  ],
  'Province of Kaduna': [
    'Gusau',
    'Ikara',
    'Kaduna',
    'Kafanchan',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kwoi',
    'Sokoto',
    'Southern Kaduna Missionary Diocese',
    'Wusasa',
    'Zaria',
    'Zonkwa',
    'Zuru',
  ],
  'Province of Kwara': [
    'Igbomina',
    'Igbomina West',
    'Idoani',
    'Jebba',
    'Kwara',
    'Offa',
    'Omu-Aran',
    'Oyun',
  ],
  'Province of Lagos': [
    'Ajayi Crowther',
    'Awori',
    'Badagry',
    'Ifo',
    'Ijebu',
    'Ijebu North',
    'Lagos',
    'Lagos Mainland',
    'Lagos South West',
    'Lagos West',
    'Remo',
    'Yewa',
  ],
  'Province of Lokoja': [
    'Evo',
    'Idah',
    'Ijumu',
    'Kabba',
    'Lokoja',
    'Ogori-Magongo',
    'Okene',
  ],
  'Province of Niger': [
    'Bida',
    'Doko',
    'Kontagora',
    'Kutigi',
    'Minna',
    'New Bussa',
    'Niger West',
  ],
  'Province of Niger Delta': [
    'Ahoada',
    'Bari',
    'Calabar',
    'Diocese on the Coast',
    'Eket',
    'Etche',
    'Ikom',
    'Ikwerre',
    'Kalabari',
    'Ndokwa',
    'Niger Delta',
    'Niger Delta North',
    'Niger Delta West',
    'Ogbaru',
    'Ogbia',
    'Ogoni',
    'Ogoja',
    'Ohaji/Egbema',
    'Okrika',
    'Omoku',
    'On the Lake',
    'On the Niger',
    'Uyo',
  ],
  'Province of Ondo': [
    'Akoko',
    'Akoko Edo',
    'Akure',
    'Ekiti',
    'Ekiti Kwara',
    'Ekiti Oke',
    'Ekiti South',
    'Ekiti West',
    'Idanre',
    'Ijesa North East',
    'Ijesha North',
    'Ilaje',
    'Ile-Oluji',
    'Irele-Eseodo',
    'Ondo',
    'Owo',
  ],
  'Province of Owerri': [
    'Aguata',
    'Amichi',
    'Awka',
    'Egbu',
    'Ideato',
    'Ihiala',
    'Ikeduru',
    'Ikka',
    'Mbaise',
    'Mbamili',
    'Nnewi',
    'Okigwe',
    'Okigwe North',
    'Okigwe South',
    'Omambala',
    'Orlu',
    'Oru',
    'Owerri',
  ],
};

/* "Other (specify)" is appended programmatically so users can type a diocese
   that doesn't appear in the official list. The same applies to provinces —
   selecting "Other" surfaces a free-text input. */
export const PROVINCE_OPTIONS = [
  ...Object.keys(PROVINCE_DIOCESE_MAP),
  'Other (specify)',
];

export const getDiocesesForProvince = (province) => {
  if (!province) return [];
  if (province === 'Other (specify)') return [];
  return PROVINCE_DIOCESE_MAP[province] || [];
};

/* Travel & transport enums */
export const TRAVEL_MODES = [
  { value: 'Air', label: 'Air' },
  { value: 'Road', label: 'Road' },
  { value: 'Rail', label: 'Rail' },
];

export const YES_NO = [
  { value: 'No', label: 'No' },
  { value: 'Yes', label: 'Yes' },
];

/* VIP/protocol levels — used by the protocol briefing page. */
export const VIP_LEVELS = [
  { value: 'regular', label: 'Delegate', description: 'Standard delegate' },
  { value: 'dignitary', label: 'Dignitary', description: 'Senior cleric or honoured guest' },
  { value: 'archbishop', label: 'Archbishop / Primate', description: 'Primate or Archbishop — highest protocol' },
  { value: 'special', label: 'Special Guest', description: 'Lay leader, faculty, honoured visitor' },
];
