/* ---------------------------------------------------------------------------
   Anglican Church of Nigeria — Ecclesiastical titles & administrative mapping.
   Source-of-truth best-effort based on the Church of Nigeria's published
   province/diocese structure. Each diocese belongs to one province; the
   registration form cascades diocese choices from the chosen province.
   --------------------------------------------------------------------------- */

export const TITLE_OPTIONS = [
  { value: 'His Grace, The Most Rev.', short: 'Most Rev.', group: 'Archbishop' },
  { value: 'His Lordship, The Rt. Rev.', short: 'Rt. Rev.', group: 'Bishop' },
  { value: 'The Very Rev.', short: 'Very Rev.', group: 'Clergy' },
  { value: 'The Ven.', short: 'Ven.', group: 'Clergy' },
  { value: 'The Rev. Canon', short: 'Rev. Canon', group: 'Clergy' },
  { value: 'The Rev.', short: 'Rev.', group: 'Clergy' },
  { value: 'Dr.', short: 'Dr.', group: 'Lay' },
  { value: 'Prof.', short: 'Prof.', group: 'Lay' },
  { value: 'Mr.', short: 'Mr.', group: 'Lay' },
  { value: 'Mrs.', short: 'Mrs.', group: 'Lay' },
  { value: 'Ms.', short: 'Ms.', group: 'Lay' },
];

export const TITLE_VALUES = TITLE_OPTIONS.map((t) => t.value);

/* Province → dioceses. Best-effort, reviewed against Church of Nigeria structure. */
export const PROVINCE_DIOCESE_MAP = {
  'Province of Aba': [
    'Aba',
    'Aba Ngwa North',
    'Arochukwu/Ohafia',
    'Isiala-Ngwa',
    'Isiala-Ngwa South',
    'Isikwuato',
    'Ngbo',
    'Ukwa',
    'Umuahia',
  ],
  'Province of Abuja': [
    'Abuja',
    'Gwagwalada',
    'Keffi',
    'Kubwa',
    'Lafia',
    'Nasarawa',
  ],
  'Province of Bendel': [
    'Asaba',
    'Benin',
    'Esan',
    'Etsako',
    'Ika',
    'Ishan',
    'Northern Izon',
    'Ozoro',
    'Sabongidda-Ora',
    'Sapele',
    'Ughelli',
    'Warri',
    'Western Izon',
  ],
  'Province of Enugu': [
    'Abakaliki',
    'Afikpo',
    'Awgu/Aninri',
    'Eha-Amufu',
    'Enugu',
    'Enugu North',
    'Ikwo',
    'Nike',
    'Nsukka',
    'Oji River',
    'Udi',
  ],
  'Province of Ibadan': [
    'Egba',
    'Egba West',
    'Ibadan',
    'Ibadan North',
    'Ibadan South',
    'Ife',
    'Ife East',
    'Ilesa',
    'Ilesa South West',
    'Ogbomoso',
    'Oke-Ogun',
    'Oke-Osun',
    'Osun',
    'Osun North',
    'Osun North East',
    'Oyo',
    'Oyo South',
  ],
  'Province of Jos': [
    'Bauchi',
    'Bukuru',
    'Damaturu',
    'Dutse',
    'Gombe',
    'Jalingo',
    'Jos',
    'Langtang',
    'Maiduguri',
    'Pankshin',
    'Takum',
    'Yola',
  ],
  'Province of Kaduna': [
    'Gusau',
    'Ikara',
    'Kaduna',
    'Kafanchan',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kwoi',
    'Southern Kaduna Missionary Diocese',
    'Wusasa',
    'Zaria',
    'Zonkwa',
    'Zuru',
  ],
  'Province of Kwara': [
    'Igbomina',
    'Igbomina West',
    'Idoani',
    'Jebba',
    'Kwara',
    'Offa',
    'Omu-Aran',
    'Oyun',
  ],
  'Province of Lagos': [
    'Ajayi Crowther',
    'Awori',
    'Badagry',
    'Ifo',
    'Ijebu',
    'Ijebu North',
    'Lagos',
    'Lagos Mainland',
    'Lagos South West',
    'Lagos West',
    'Remo',
    'Yewa',
  ],
  'Province of Lokoja': [
    'Idah',
    'Ijumu',
    'Kabba',
    'Lokoja',
    'Ogori-Magongo',
    'Okene',
  ],
  'Province of Niger': [
    'Bida',
    'Kontagora',
    'Kutigi',
    'Minna',
    'New Bussa',
  ],
  'Province of Niger Delta': [
    'Ahoada',
    'Bari',
    'Etche',
    'Ikwerre',
    'Kalabari',
    'Ndokwa',
    'Niger Delta',
    'Niger Delta North',
    'Niger Delta West',
    'Ogbaru',
    'Ogbia',
    'Ogoni',
    'Ohaji/Egbema',
    'Okrika',
    'Omoku',
    'On the Lake',
    'On the Niger',
  ],
  'Province of Ondo': [
    'Akoko',
    'Akoko Edo',
    'Akure',
    'Ekiti',
    'Ekiti Kwara',
    'Ekiti Oke',
    'Ekiti South',
    'Ekiti West',
    'Idanre',
    'Ijesa North East',
    'Ijesha North',
    'Ile-Oluji',
    'Ilesa',
    'Irele-Eseodo',
    'Ondo',
    'Owo',
  ],
  'Province of Owerri': [
    'Aguata',
    'Amichi',
    'Awka',
    'Egbu',
    'Ideato',
    'Ihedioranma',
    'Ihiala',
    'Ikeduru',
    'Mbaise',
    'Mbamili',
    'Nnewi',
    'Ogbaru',
    'Okigwe',
    'Okigwe North',
    'Okigwe South',
    'Omambala',
    'Orlu',
    'Oru',
    'Owerri',
  ],
};

export const PROVINCE_OPTIONS = Object.keys(PROVINCE_DIOCESE_MAP);

export const getDiocesesForProvince = (province) => {
  if (!province) return [];
  return PROVINCE_DIOCESE_MAP[province] || [];
};

/* "Other affiliation" suggestions — non-diocesan bodies often represented at
   Episcopal Consultations. Free-text field accepts any value; this list
   is just for datalist suggestions. */
export const AFFILIATION_SUGGESTIONS = [
  'Church of Nigeria Headquarters',
  'Vining College of Theology',
  'Crowther Graduate School of Theology',
  'Ajayi Crowther University',
  'Providence University',
  'Bishop on the Lakes',
  'Anglican Consultative Council',
  'Global Anglican Future Conference (GAFCON)',
  'Diocesan Board / Secretariat',
  "Spouse of Bishop",
  'Chancellor / Legal Adviser',
  'Personal Aide',
];

/* Travel & transport enums */
export const TRAVEL_MODES = [
  { value: 'Air', label: 'Air' },
  { value: 'Road', label: 'Road' },
  { value: 'Rail', label: 'Rail' },
];

export const YES_NO = [
  { value: 'No', label: 'No' },
  { value: 'Yes', label: 'Yes' },
];
