export const TITLE_OPTIONS = ['Most Rev.', 'Rt. Rev.'];

export const PROVINCE_OPTIONS = [
  'Province of Aba',
  'Province of Abuja',
  'Province of Bendel',
  'Province of Enugu',
  'Province of Ibadan',
  'Province of Jos',
  'Province of Kaduna',
  'Province of Kwara',
  'Province of Lagos',
  'Province of Lokoja',
  'Province of Niger',
  'Province of Niger Delta',
  'Province of Ondo',
  'Province of Owerri',
];

export const DIOCESE_OPTIONS = [
  'Aba',
  'Aba Ngwa North',
  'Abakaliki',
  'Abuja',
  'Afikpo',
  'Aguata',
  'Ahoada',
  'Ajayi Crowther',
  'Akoko',
  'Akoko Edo',
  'Akure',
  'Amichi',
  'Arochukwu/Ohafia',
  'Asaba',
  'Awgu/Aninri',
  'Awka',
  'Awori',
  'Badagry',
  'Bari',
  'Bauchi',
  'Benin',
  'Bida',
  'Bukuru',
  'Calabar',
  'Damaturu',
  'Diocese on the Coast',
  'Doko',
  'Dutse',
  'Egba',
  'Egba West',
  'Egbu',
  'Eha-Amufu',
  'Eket',
  'Ekiti',
  'Ekiti Kwara',
  'Ekiti Oke',
  'Ekiti South',
  'Ekiti West',
  'Enugu',
  'Enugu North',
  'Esan',
  'Etche',
  'Etsako',
  'Evo',
  'Gboko',
  'Gombe',
  'Gusau',
  'Gwagwalada',
  'Ibadan',
  'Ibadan North',
  'Ibadan South',
  'Idah',
  'Idanre',
  'Ideato',
  'Idoani',
  'Ife',
  'Ife East',
  'Ifo',
  'Igbomina',
  'Igbomina West',
  'Ihiala',
  'Ijebu',
  'Ijebu North',
  'Ijesa North East',
  'Ijesha North',
  'Ijumu',
  'Ikara',
  'Ikeduru',
  'Ikka',
  'Ikom',
  'Ikwerre',
  'Ikwo',
  'Ikwuano',
  'Ilaje',
  'Ile-Oluji',
  'Ilesa',
  'Ilesa South West',
  'Irele-Eseodo',
  'Isiala-Ngwa',
  'Isiala-Ngwa South',
  'Isikwuato',
  'Jalingo',
  'Jebba',
  'Jos',
  'Kabba',
  'Kaduna',
  'Kafanchan',
  'Kalabari',
  'Kano',
  'Katsina',
  'Kebbi',
  'Keffi',
  'Kontagora',
  'Kubwa',
  'Kutigi',
  'Kwara',
  'Kwoi',
  'Lafia',
  'Lagos',
  'Lagos Mainland',
  'Lagos South West',
  'Lagos West',
  'Langtang',
  'Lokoja',
  'Maiduguri',
  'Makurdi',
  'Mbaise',
  'Mbamili',
  'Minna',
  'Nasarawa',
  'Ndokwa',
  'New Bussa',
  'Ngbo',
  'Niger Delta',
  'Niger Delta North',
  'Niger Delta West',
  'Niger West',
  'Nike',
  'Nnewi',
  'Northern Izon',
  'Nsukka',
  'Offa',
  'Ogbaru',
  'Ogbia',
  'Ogbomoso',
  'Ogoni',
  'Ogori-Magongo',
  'Ogoja',
  'Ohaji/Egbema',
  'Oji River',
  'Oke-Ogun',
  'Oke-Osun',
  'Okene',
  'Okigwe',
  'Okigwe North',
  'Okigwe South',
  'Okrika',
  'Omu-Aran',
  'Omoku',
  'On the Lake',
  'On the Niger',
  'Ondo',
  'Orlu',
  'Oru',
  'Osun',
  'Osun North',
  'Osun North East',
  'Otukpo',
  'Owerri',
  'Owo',
  'Oyo',
  'Oyo South',
  'Oyun',
  'Ozoro',
  'Pankshin',
  'Remo',
  'Sabongidda-Ora',
  'Sapele',
  'Sokoto',
  'Takum',
  'Udi',
  'Ughelli',
  'Ukwa',
  'Umuahia',
  'Uyo',
  'Warri',
  'Western Izon',
  'Wusasa',
  'Yewa',
  'Yola',
  'Zaki-Biam',
  'Zaria',
  'Zonkwa',
  'Zuru',
  'Omambala',
  'Southern Kaduna Missionary Diocese',
];
